apply plugin: 'com.android.application'

android {
    namespace = 'cn.bingoogolapple.progressbar.demo'
    compileSdkVersion ANDROID_BUILD_SDK_VERSION as int

    defaultConfig {
        minSdkVersion ANDROID_BUILD_MIN_SDK_VERSION as int
        targetSdkVersion ANDROID_BUILD_TARGET_SDK_VERSION as int
        versionCode VERSION_CODE as int
        versionName VERSION_NAME
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation project(':library')
//    implementation "cn.bingoogolapple:bga-progressbar:${VERSION_NAME}@aar"
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
